apiVersion: v1
kind: Service

metadata:
  name: company-intranet-service

spec:
  type: NodePort

  selector:
    app: company-intranet

  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081